using System.Text;
using System.Text.Json;

if (!TryParseArgs(args, out var options, out var parseError))
{
    Console.Error.WriteLine(parseError);
    Console.Error.WriteLine("Usage: dotnet run --project FastDrawingVisual.CommandProtocol -- --schema <path> --out-dir <path>");
    return 1;
}

var schema = LoadSchema(options.SchemaPath);
ValidateSchema(schema);

Directory.CreateDirectory(options.OutputDirectory);

var csPath = Path.Combine(options.OutputDirectory, "BridgeCommandProtocol.g.cs");
var cppPath = Path.Combine(options.OutputDirectory, "BridgeCommandProtocol.g.h");

File.WriteAllText(csPath, GenerateCSharp(schema), new UTF8Encoding(false));
File.WriteAllText(cppPath, GenerateCppHeader(schema), new UTF8Encoding(false));

Console.WriteLine($"Generated:");
Console.WriteLine($"  {csPath}");
Console.WriteLine($"  {cppPath}");
return 0;

static Schema LoadSchema(string schemaPath)
{
    if (!File.Exists(schemaPath))
        throw new FileNotFoundException($"Schema not found: {schemaPath}");

    var json = File.ReadAllText(schemaPath);
    var schema = JsonSerializer.Deserialize<Schema>(json, new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true
    });

    if (schema is null)
        throw new InvalidOperationException($"Failed to deserialize schema: {schemaPath}");

    return schema;
}

static void ValidateSchema(Schema schema)
{
    if (string.IsNullOrWhiteSpace(schema.Name))
        throw new InvalidOperationException("Schema.name is required.");

    if (!string.Equals(schema.Endianness, "little", StringComparison.OrdinalIgnoreCase))
        throw new InvalidOperationException("Only little endianness is supported.");

    if (schema.Commands.Count == 0)
        throw new InvalidOperationException("Schema.commands must not be empty.");

    var seenNames = new HashSet<string>(StringComparer.Ordinal);
    var seenIds = new HashSet<int>();
    foreach (var cmd in schema.Commands)
    {
        if (string.IsNullOrWhiteSpace(cmd.Name))
            throw new InvalidOperationException("Command.name is required.");
        if (!seenNames.Add(cmd.Name))
            throw new InvalidOperationException($"Duplicate command name: {cmd.Name}");
        if (!seenIds.Add(cmd.Id))
            throw new InvalidOperationException($"Duplicate command id: {cmd.Id}");
        if (cmd.Id <= 0 || cmd.Id > 255)
            throw new InvalidOperationException($"Command id must be 1..255: {cmd.Name}={cmd.Id}");
        if (cmd.Fields.Count == 0)
            throw new InvalidOperationException($"Command {cmd.Name} must contain at least one field.");

        var fieldNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var field in cmd.Fields)
        {
            if (string.IsNullOrWhiteSpace(field.Name))
                throw new InvalidOperationException($"Command {cmd.Name} has empty field name.");
            if (!fieldNames.Add(field.Name))
                throw new InvalidOperationException($"Command {cmd.Name} has duplicate field name: {field.Name}");
            _ = GetTypeSize(field.Type);
        }
    }
}

static bool TryParseArgs(string[] args, out CliOptions options, out string error)
{
    options = new CliOptions("", "");
    error = string.Empty;

    string schema = "";
    string outDir = "";

    for (var i = 0; i < args.Length; i++)
    {
        var arg = args[i];
        if (string.Equals(arg, "--schema", StringComparison.OrdinalIgnoreCase))
        {
            if (i + 1 >= args.Length)
            {
                error = "--schema requires a value.";
                return false;
            }

            schema = args[++i];
            continue;
        }

        if (string.Equals(arg, "--out-dir", StringComparison.OrdinalIgnoreCase))
        {
            if (i + 1 >= args.Length)
            {
                error = "--out-dir requires a value.";
                return false;
            }

            outDir = args[++i];
            continue;
        }

        error = $"Unknown argument: {arg}";
        return false;
    }

    if (string.IsNullOrWhiteSpace(schema))
    {
        error = "Missing required --schema argument.";
        return false;
    }

    if (string.IsNullOrWhiteSpace(outDir))
    {
        error = "Missing required --out-dir argument.";
        return false;
    }

    options = new CliOptions(schema, outDir);
    return true;
}

static string GenerateCSharp(Schema schema)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine($"// Source: {Path.GetFileName("command_protocol.schema.json")}");
    sb.AppendLine("namespace FastDrawingVisual.CommandProtocol");
    sb.AppendLine("{");
    sb.AppendLine("    internal enum BridgeCommandType : byte");
    sb.AppendLine("    {");
    foreach (var cmd in schema.Commands.OrderBy(c => c.Id))
    {
        sb.AppendLine($"        {cmd.Name} = {cmd.Id},");
    }

    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    internal static class BridgeCommandLayout");
    sb.AppendLine("    {");
    foreach (var cmd in schema.Commands.OrderBy(c => c.Id))
    {
        var payloadSize = GetPayloadSize(cmd);
        sb.AppendLine($"        internal const int {cmd.Name}PayloadBytes = {payloadSize};");
        sb.AppendLine($"        internal const int {cmd.Name}CommandBytes = 1 + {cmd.Name}PayloadBytes;");

        var offset = 0;
        foreach (var field in cmd.Fields)
        {
            sb.AppendLine($"        internal const int {cmd.Name}{field.Name}Offset = {offset};");
            offset += GetTypeSize(field.Type);
        }

        sb.AppendLine();
    }

    sb.AppendLine("    }");
    sb.AppendLine("}");
    return sb.ToString();
}

static string GenerateCppHeader(Schema schema)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("// Source: command_protocol.schema.json");
    sb.AppendLine("#pragma once");
    sb.AppendLine();
    sb.AppendLine("#include <cstdint>");
    sb.AppendLine();
    sb.AppendLine("namespace fdv::protocol {");
    sb.AppendLine("enum class CommandType : std::uint8_t {");
    foreach (var cmd in schema.Commands.OrderBy(c => c.Id))
    {
        sb.AppendLine($"  {cmd.Name} = {cmd.Id},");
    }

    sb.AppendLine("};");
    sb.AppendLine();
    foreach (var cmd in schema.Commands.OrderBy(c => c.Id))
    {
        var payloadSize = GetPayloadSize(cmd);
        sb.AppendLine($"static constexpr std::uint8_t kCmd{cmd.Name} = static_cast<std::uint8_t>(CommandType::{cmd.Name});");
        sb.AppendLine($"static constexpr int k{cmd.Name}PayloadBytes = {payloadSize};");
        sb.AppendLine($"static constexpr int k{cmd.Name}CommandBytes = 1 + k{cmd.Name}PayloadBytes;");

        var offset = 0;
        foreach (var field in cmd.Fields)
        {
            sb.AppendLine($"static constexpr int k{cmd.Name}{field.Name}Offset = {offset};");
            offset += GetTypeSize(field.Type);
        }

        sb.AppendLine();
    }

    sb.AppendLine("} // namespace fdv::protocol");
    return sb.ToString();
}

static int GetPayloadSize(CommandSchema command)
{
    var total = 0;
    foreach (var field in command.Fields)
    {
        total += GetTypeSize(field.Type);
    }

    return total;
}

static int GetTypeSize(string type)
{
    return type switch
    {
        "f32" => 4,
        "color_argb8" => 4,
        _ => throw new InvalidOperationException($"Unsupported field type: {type}")
    };
}

internal sealed record CliOptions(string SchemaPath, string OutputDirectory);

internal sealed class Schema
{
    public string Name { get; init; } = "";
    public string Endianness { get; init; } = "little";
    public string ColorLayout { get; init; } = "A,R,G,B";
    public List<CommandSchema> Commands { get; init; } = new();
}

internal sealed class CommandSchema
{
    public string Name { get; init; } = "";
    public int Id { get; init; }
    public List<FieldSchema> Fields { get; init; } = new();
}

internal sealed class FieldSchema
{
    public string Name { get; init; } = "";
    public string Type { get; init; } = "";
}
